### ISSUE TITLE
My NFTs menu option is not showing on node

### ISSUE THREAD

**Issue by MirekR** [bitclout/core#84]
Hi,
  I've tried to update our node to start supporting NFTs, using the "stable" docker images for backend and frontend (see the docker-compose attached), it's still now showing in the menu.
<img width="234" alt="Screenshot 2021-07-29 at 16 16 52" src="https://user-images.githubusercontent.com/9283797/127518568-35e9456c-463b-47d1-bf82-a67a65d3b81e.png">

From the discussion on the discord, recommendation is to wipe out database and resync again. That seems to be odd considering it should be new feature not related to previous Transactions / Blokcs, plus loosing our global feed is not optimal either. 
<img width="1494" alt="Screenshot 2021-07-29 at 16 19 48" src="https://user-images.githubusercontent.com/9283797/127519176-48ef07af-749c-4834-aa26-3f0f25f4446f.png">

Any suggesting how to progress and get the NFTs available on our node without wiping database? 

Thanks.

**Comment by MirekR** [comment]
```
version: "3.7"
services:
  backend:
    container_name: backend
    image: docker.io/bitclout/backend:stable
    command: run
    volumes:
    - db:/db
    - ./:/bitclout/run  
    ports:
    - 17001:17001
    - 17000:17000
    env_file:
    - dev.env
    expose:
    - "17001"
    - "17000"
  frontend:
    container_name: frontend 
    image: docker.io/bitclout/frontend:stable
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    env_file:
    - dev.env
    expose:
    - "8080"
  nginx: 
    container_name: nginx
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on: 
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  db:
```
